
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 07 12:53:17 ART 2025
//----------------------------------------------------

package com.grupo2.tpteo1grupo2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENDDECLARE_SECTION = 32;
  public static final int OP_MAYOR = 21;
  public static final int ABRIR_CORCHETE = 37;
  public static final int PUNTO_Y_COMA = 39;
  public static final int INTEGER = 10;
  public static final int CONST_B = 19;
  public static final int WRITE = 8;
  public static final int OP_DIV = 28;
  public static final int CON_OR = 16;
  public static final int IF = 2;
  public static final int ID = 13;
  public static final int ENDWHILE = 7;
  public static final int CERRAR_PARENTESIS = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int OP_MULT = 27;
  public static final int OP_RESTA = 26;
  public static final int ABRIR_PARENTESIS = 35;
  public static final int OPLIST = 12;
  public static final int OP_MAYOR_IGUAL = 24;
  public static final int DECLARACION = 30;
  public static final int CERRAR_CORCHETE = 38;
  public static final int ENDIF = 5;
  public static final int ELSE = 4;
  public static final int OP_IGUAL = 22;
  public static final int WHILE = 6;
  public static final int FLOAT = 9;
  public static final int OP_MENOR_IGUAL = 23;
  public static final int THEN = 3;
  public static final int CONST_STRING = 18;
  public static final int PROGRAM_SECTION = 33;
  public static final int ASIGN = 29;
  public static final int STRING = 11;
  public static final int ENDPROGRAM_SECTION = 34;
  public static final int CON_AND = 17;
  public static final int OP_SUMA = 25;
  public static final int CONST_REAL = 15;
  public static final int OP_MENOR = 20;
  public static final int CONST_INT = 14;
  public static final int DECLARE_SECTION = 31;
}

