
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 24 21:25:25 ART 2024
//----------------------------------------------------

package com.grupo2.tpteo1grupo2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABRIR_LLAVE = 37;
  public static final int ENDDECLARE_SECTION = 32;
  public static final int INTERROGACION = 43;
  public static final int OP_MAYOR = 20;
  public static final int ABRIR_CORCHETE = 39;
  public static final int PUNTO_Y_COMA = 41;
  public static final int INTEGER = 11;
  public static final int CONST_B = 18;
  public static final int WRITE = 9;
  public static final int OP_DIV = 27;
  public static final int ENDFOR = 8;
  public static final int IF = 2;
  public static final int ID = 14;
  public static final int ENDWHILE = 7;
  public static final int CERRAR_PARENTESIS = 36;
  public static final int EOF = 0;
  public static final int CON_LOGICO = 28;
  public static final int error = 1;
  public static final int COMA = 44;
  public static final int OP_MULT = 26;
  public static final int CERRAR_LLAVE = 38;
  public static final int OP_RESTA = 25;
  public static final int ADMIRACION = 42;
  public static final int DECLARATION = 30;
  public static final int ABRIR_PARENTESIS = 35;
  public static final int OPLIST = 13;
  public static final int OP_MAYOR_IGUAL = 23;
  public static final int CERRAR_CORCHETE = 40;
  public static final int ENDIF = 5;
  public static final int ELSE = 4;
  public static final int OP_IGUAL = 21;
  public static final int WHILE = 6;
  public static final int FLOAT = 10;
  public static final int OP_MENOR_IGUAL = 22;
  public static final int THEN = 3;
  public static final int CONST_STRING = 17;
  public static final int PROGRAM_SECTION = 33;
  public static final int ASIGN = 29;
  public static final int STRING = 12;
  public static final int ENDPROGRAM_SECTION = 34;
  public static final int OP_SUMA = 24;
  public static final int CONST_REAL = 16;
  public static final int OP_MENOR = 19;
  public static final int CONST_INT = 15;
  public static final int DECLARE_SECTION = 31;
}

